"""add table face

Revision ID: c6eb3641018e
Revises: bf8f53fff149
Create Date: 2021-08-05 22:16:27.620850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6eb3641018e'
down_revision = 'bf8f53fff149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
